import PDFDocument from 'pdfkit'

export function pdfRoute(req, res) {
  try {
    const { diagnosis, severity, explanation, recommended_action, when_to_see_doctor } = req.body

    const doc = new PDFDocument({ margin: 50 })
    res.setHeader('Content-Type', 'application/pdf')
    res.setHeader('Content-Disposition', 'attachment; filename="medical-report.pdf"')

    doc.pipe(res)

    // Header
    doc.fontSize(24).font('Helvetica-Bold').text('Medical Symptom Analysis Report', { align: 'center' })
    doc.moveDown(0.5)
    doc.fontSize(10).font('Helvetica').text(`Generated: ${new Date().toLocaleString()}`, { align: 'center' })
    doc.moveDown(1)

    // Divider
    doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke()
    doc.moveDown(0.5)

    // Severity Section
    doc.fontSize(14).font('Helvetica-Bold').text('Severity Level')
    doc.fontSize(12).font('Helvetica').text(severity, { color: getSeverityColor(severity) })
    doc.moveDown(0.5)

    // Diagnosis Section
    doc.fontSize(14).font('Helvetica-Bold').text('Possible Conditions')
    diagnosis.forEach((condition) => {
      doc.fontSize(11).text(`• ${condition}`)
    })
    doc.moveDown(0.5)

    // Divider
    doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke()
    doc.moveDown(0.5)

    // Explanation
    doc.fontSize(14).font('Helvetica-Bold').text('Medical Explanation')
    doc.fontSize(11).font('Helvetica').text(explanation || 'N/A', { align: 'justify' })
    doc.moveDown(0.5)

    // Recommended Action
    doc.fontSize(14).font('Helvetica-Bold').text('Recommended Action')
    doc.fontSize(11).font('Helvetica').text(recommended_action || 'N/A', { align: 'justify' })
    doc.moveDown(0.5)

    // When to See Doctor
    doc.fontSize(14).font('Helvetica-Bold').text('When to See a Doctor')
    doc.fontSize(11).font('Helvetica').text(when_to_see_doctor || 'N/A', { align: 'justify' })
    doc.moveDown(1)

    // Divider
    doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke()
    doc.moveDown(0.5)

    // Disclaimer
    doc.fontSize(10).font('Helvetica-Oblique').text(
      'DISCLAIMER: This report is generated by AI and is for informational purposes only. It does not constitute medical advice. Please consult a qualified healthcare professional for accurate diagnosis and treatment.',
      { align: 'justify', color: '#666666' }
    )

    doc.end()
  } catch (error) {
    console.error('PDF generation error:', error)
    res.status(500).json({ error: error.message })
  }
}

function getSeverityColor(severity) {
  const colors = {
    'Low': '#10b981',
    'Medium': '#f59e0b',
    'High': '#ef4444',
    'Critical': '#991b1b'
  }
  return colors[severity] || '#000000'
}
